# @package _global_
# ! Primary hydra config for ALL models
defaults:
  - _self_ # To be overwritten by experimental settings
  - user: env
  - data: covid
  - llm: llama_peft
  - model: covid_llm
  - optional template: ${model}/${data}
  - prompt: prompts
  - exp: sft
  - override /hydra/hydra_logging@_group_: none # Disable Hydra logging
  - override /hydra/job_logging@_group_: none # Disable Hydra logging

debug: false

# ! Experiments
seed: 2023
distributed_port: 29499
# ! Path
# @ Note that path end with /, file end without /
path:
  data_cache: data_cache/
  data_storage: data/
  temp: temp/ # Removable
  out_dir: output/ #
  hf_local: /scratch4/haofrankyang/yang/hf/

working_dir: ${path.temp}working_dir/${.uid}/ # For deletable temporary files.
out_dir: ${path.out_dir}${oc.select:wandb.sweep_id,local}/${model.name}/${.uid}-${.alias}/ # For files to be saved, to be initialized
uid: null # To be generated in the main program
#
eval_freq: 50
best_eval_metrics: "val_mse"
max_best_eval_metrics: false   # minimize the mse
use_wandb: false
# alias: ${llm.name}${data.build_func}${data.name}
alias: ${target}-${splits_type}-${lr}
wandb:
  id: null
  name: ${alias}

slurm_id: ${oc.env:SLURM_JOB_ID,null}
logging:
  level: info
  log_wandb_metric_to_stdout: False
code_version: 2.3

# @ ??
hydra:
  run:
    dir: ../temp/hydra/${now:%Y.%m.%d}/${now:%H.%M.%S}

# ! _file_ related
_unimportant_cfg:
  fields: [ gpus, debug, wandb, proj, env, uid,
            local_rank, cmd, label_name, logging,
            use_wandb, n_nodes, n_labels, alias
  ]
  postfix: [ _path, _file, _dir, _url ]
  prefix: [ _ ]